### ISSUE TITLE
规则引擎的选型

### ISSUE THREAD

**Issue by mbigger** [jetlinks/rule-engine#3]
符合JSR94规范的规则引擎有很多，Drools，Mandarax，OpenRules等，Jetlinks自己实现规则引擎出于何种考虑，就功能而言，jetlinks的rule-engine有何特点？

**Comment by zhou-hao** [comment]
此规则引擎非彼规则引擎， jetlinks的规则引擎更像一个 工作流，基于reactor的数据流引擎。可视化配置，分布式调度等。 

![image](https://user-images.githubusercontent.com/7791838/87136738-7deda800-c2ce-11ea-91d4-ba5ee759bdf7.png)

**Comment by tanhx** [comment]
我怎么联系你们？
主页上的QQ号，第一个324606263让去找第二个647954464，第二个让输验证字。
盲猜jetlink进去了，但始终没人通过验证。
